{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "source-websocket.fullname" . }}
  labels:
    {{- include "source-websocket.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "source-websocket.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Object
      object:
        describedObject:
          kind: Service
          name: "{{ .Values.autoscaling.resolver.name }}"
        metric:
          name: "awk_work_queue_capacity"
          selector:
            matchLabels:
              name: "{{ .Values.autoscaling.resolver.queue.name }}"
              threshold: "{{ .Values.autoscaling.resolver.queue.capacity.threshold }}"
        target:
          type: Value
          value: "{{ .Values.autoscaling.resolver.queue.capacity.target }}"
    {{- if .Values.autoscaling.targetCPUUtilizationValue }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: {{ .Values.autoscaling.targetCPUUtilizationValue }}
    {{- end }}
    {{- if .Values.autoscaling.targetMemoryUtilizationValue }}
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: {{ .Values.autoscaling.targetMemoryUtilizationValue }}
    {{- end }}
{{- end }}
